trigger:
- master

resources:
  repositories:
  - repository: MSDYN365BC_Yaml
    type: github
    name: kine/MSDYN365BC_Yaml
    ref: 'refs/heads/master'
    endpoint: GitHub
  - repository: self
    checkoutOptions:
      submodules: true

variables:
  TestCodeunitId: 130402
  # Define variable USER.PASSWORD for password of the user account under which the agent runs
  # Define variable CertPassword for cetificate password
  # Define variable CertFile for path and name of the certificate
  UserPwd: $(USER.PASSWORD)
  CertPwd: $(CertPassword)

queue:
  name: default
  #demands: Docker

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'

- template: Templates/PrepareEnv.yml@MSDYN365BC_Yaml
  parameters:
    pwd: $(UserPwd)

- template: Templates/DownloadSymbols.yml@MSDYN365BC_Yaml
  parameters:
    pwd: $(UserPwd)

- template: Templates/CompileALApps.yml@MSDYN365BC_Yaml
  parameters:
    CertPath: $(CertFile)
    CertPwd: $(CertPwd)

- template: Templates/InstallALApps.yml@MSDYN365BC_Yaml
  parameters:
    CertPath: $(CertFile)

- template: Templates/TestALApp.yml@MSDYN365BC_Yaml
  parameters:
    TrxFile: TestResults.trx
    TestCodeunitId: $(TestCodeunitId)
    pwd: $(UserPwd)

- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: App'
  inputs:
    ArtifactName: App


- task: PublishTestResults@2

  displayName: 'Publish Test Results **\Test*.trx'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**\Test*.trx'
  condition: succeededOrFailed()


- template: Templates/RemoveEnv.yml@MSDYN365BC_Yaml
