trigger:
- master

resources:
  repositories:
  #To use the templates, create first Service connection in your Azure DevOps project to GitHub, named GitHub    
  - repository: MSDYN365BC_Yaml
    type: github
    name: kine/MSDYN365BC_Yaml
    ref: 'refs/heads/master'
    endpoint: GitHub
  - repository: self

variables:
  UserPwd: 'pass@word1'
  CertPath: 'c:\Cert\CodeSigning.p12'
  CertPwd: 'CertPwd'
  TestCodeunitId: 130402

queue:
  name: default

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'

- template: Templates/PrepareEnv.yml@MSDYN365BC_Yaml
  parameters:
    pwd: $(UserPwd)

- template: Templates/DownloadSymbols.yml@MSDYN365BC_Yaml
  parameters:
    pwd: $(UserPwd)

- template: Templates/CompileALApps.yml@MSDYN365BC_Yaml
  parameters:
    CertPath: $(CertPath)
    CertPwd: $(CertPassword)

- template: Templates/InstallALApps.yml@MSDYN365BC_Yaml
  parameters:
    CertPath: $(CertPath)

- template: Templates/TestALApp.yml@MSDYN365BC_Yaml
  parameters:
    TrxFile: TestResults.trx
    TestCodeunitId: $(TestCodeunitId)

- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: App'
  inputs:
    ArtifactName: App


- task: PublishTestResults@2

  displayName: 'Publish Test Results **\Test*.trx'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**\Test*.trx'
  condition: succeededOrFailed()


- template: Templates/RemoveEnv.yml@MSDYN365BC_Yaml
